version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/screwyprof/payment
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: ./tools/test.sh
      - codecov/upload:
          file: coverage.txt